### ISSUE TITLE
descripe not explicit

### ISSUE THREAD

**Issue by autodataming** [Pymol-Scripts/Pymol-script-repo#83]
http://www.pymolwiki.org/index.php/Selection_Algebra
operator    distance is ...     measured from   includes s2     syntax  notes 
around  ≤ X                     center                    never                       2                            

center means  one neareast atom in x, not the center of x
for example x=benzene,
iterate every atom in ben ,the get set for every atom,
final combine all the sets.

**Comment by aloctavodia** [comment]
I am not sure to understand your problem I also I think your comment is better suited for the PyMOL [mailing list](http://www.mail-archive.com/pymol-users@lists.sourceforge.net/info.html), because is not an issue with a plugin in this repository, so I am closing this. Feel free to send and e-mail to the mailing list.
